apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.component_id}}-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ${{ values.component_id }}
        image: ghcr.io/gattma/${{ values.component_id }}:latest
        ports:
        - containerPort: 8080