apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}-ci
  description: ${{values.description | dump}}
  tags:
    - kustomize
    - argocd
  links:
    - url: https://localhost:8080
      title: WebApp Endpoint
      icon: web
  annotations:
    'github.com/project-slug': gattma/${{values.artifact_id}}-ci
    'backstage.io/kubernetes-id': ${{values.artifact_id}}-ci
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  system: ${{values.application}}