apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}-initializer-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gattma/${{ values.component_id}}-ci.git
    targetRevision: master
    path: appsets/
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.component_id }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated: 
      prune: true 
      selfHeal: true